In [2]:
colors=['red', 'green', 'yellow', 'purple']
for i in range(len(colors)-1,-1,-1):
    print(colors[i],end=" ")

purple yellow green red 

In [4]:
for color in reversed(colors):
    print(color,end=" ")

purple yellow green red 

In [5]:
import pandas as pd

In [16]:
dt = {'Id':[11,12,13,14,15],
     'first_name':['A','B','C','D','E'],
     'company':['aa','bb','cc','dd','ee'],
     'address':['Hyd','Hyd', 'Hyd', 'Hyd', 'Hyd']}
mydt = pd.DataFrame(dt)
mydt

Id first_name company address
0  11          A      aa     Hyd
1  12          B      bb     Hyd
2  13          C      cc     Hyd
3  14          D      dd     Hyd
4  15          E      ee     Hyd

In [17]:
import os

In [28]:
os.chdir("D:\SOFTWARE")

In [35]:
mydt.to_csv('Bala.csv')

In [37]:
pd.read_csv('Bala.csv')

Unnamed: 0  Id first_name company address
0           0  11          A      aa     Hyd
1           1  12          B      bb     Hyd
2           2  13          C      cc     Hyd
3           3  14          D      dd     Hyd
4           4  15          E      ee     Hyd

### print only Two Columns
### Print the large value from CustilD column -- max
### Print the least value from CustilD column -- min

### Numpy - Working with multi dimensional array
- Numpy arrays is a bit like Python list
- Nupy array is data structure of Numpy Lib
- it's short name for Numeric Python 


In [41]:
import numpy as np

In [42]:
li = [1,2,3,4,5]
print(li,end=" ")


[1, 2, 3, 4, 5] 

In [44]:
array=np.array(li)
print(array)

[1 2 3 4 5]


In [48]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2=np.array([(1,2),(2,3),(4,5)])
print(a2.shape)

(2, 3)
(3, 2)


In [49]:
a1=np.array([(1,2,3)])
a2=np.array([(4,5,6)])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]
